version: '3.8'

x-airflow-common: &airflow-common
  build:
    context: ../        
    dockerfile: docker/airflow/Dockerfile
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    _PIP_ADDITIONAL_REQUIREMENTS: "--no-cache-dir -r /requirements.txt"
  volumes:
    - ../etl/dags:/opt/airflow/dags
    - ../etl/logs:/opt/airflow/logs
    - ./airflow/requirements.txt:/requirements.txt
    - ../data:/opt/airflow/data
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - data_network

  mysql:
    image: mysql/mysql-server:latest
    container_name: bio_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bio_project
      MYSQL_USER: bio_user
      MYSQL_PASSWORD: bio_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - data_network

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init && \
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email trunghieu201297@gmail.com
    networks:
      - data_network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: always
    networks:
      - data_network

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: always
    networks:
      - data_network

  dbt:
    container_name: dbt
    build:
      context: ./dbt
    volumes:
      - ../dwh:/app/dwh
    working_dir: /app/dwh
    command: ["dbt", "run"]
    networks:
      - data_network
    depends_on:
      - postgres
    restart: unless-stopped

  mlflow:
    container_name: mlflow
    build:
      context: ./mlflow
    ports:
      - "5000:5000"
    volumes:
      - ../mlruns:/mlflow/mlruns
    environment:
      MLFLOW_TRACKING_URI: "http://0.0.0.0:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root ./mlruns
    networks:
      - data_network
    restart: unless-stopped

volumes:
  postgres_data:
  mysql_data:

networks:
  data_network:
    driver: bridge
